const data = {
    products:[
       
        {
            _id:'1',
            name:'Nike Slim Shrit',
            category:'Shirt',
            image:'./images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'adidas Slim Shrit',
            category:'Shirt',
            image:'./images/p2.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'lacosta Slim Shrit',
            category:'Shirt',
            image:'./images/p3.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim pant',
            category:'pant',
            image:'./images/p4.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'puma',
            name:'Nike Slim pant',
            category:'pant',
            image:'./images/p5.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'6 Slim Shrit',
            category:'Shirt',
            image:'./images/p6.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ]
}
export default data;